# Jekyll configuration

name: yashendaoren
title: yashendaoren 的主页
author: yashendaoren && Aigars Dzerviniks
description: Welcome to yashendaoren 的主页! - iOS开发 微信小程序开发 前端开发

highlighter: null
permalink: /:title

url:
baseurl:
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 500

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
